routeEnhancers:
  OkAzureLogin:
    type: Extbase
    extension: OkAzureLogin
    plugin: Login
    routes:
      - routePath: '/redirectURI'
        _controller: 'Login::login'
    defaultController: 'Login::show'
    aspects: {}
