routeEnhancers:
  OkAzureLogin:
    type: Extbase
    extension: OkAzureLogin
    plugin: Pi1
    routes:
      - { routePath: '/azure-login', _controller: 'AzureLogin::login', _arguments: {} }
    defaultController: 'AzureLogin::login'
    aspects: {}
