services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OliverKroener\OkAzureLogin\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  OliverKroener\OkAzureLogin\Authentication\AzureLoginAuthService:
    tags:
      - name: 'typo3.authentication'
        priority: 50
        subType: 'getUserBE'
        position: 'before'
